export type Lang = 'en' | 'ar'

export const CONTACT = {
  name: 'Ayman Milad',
  brand: 'Ask Ayman',
  phoneDisplay: '+20 109 100 0160',
  phoneTel: '+201091000160',
  whatsapp: 'https://wa.me/201091000160',
  email: 'ayman.mina.can@gmail.com',
  addressEn: '36 El-Ahram St, Heliopolis, Cairo, Egypt',
  addressAr: '٣٦ شارع الأهرام، مصر الجديدة، القاهرة',
  facebook:
    'https://www.facebook.com/p/Ayman-Milad-Property-Consultant-100083253733071/',
  instagram: 'https://www.instagram.com/aymanmilad_property_consultant/',
}

export const VIDEOS = [
  'https://videos.pexels.com/video-files/7578552/7578552-hd_1920_1080_30fps.mp4',
  'https://videos.pexels.com/video-files/10135156/10135156-hd_1920_1080_30fps.mp4',
  'https://videos.pexels.com/video-files/7578546/7578546-hd_1920_1080_30fps.mp4',
  'https://videos.pexels.com/video-files/5744421/5744421-hd_1920_1080_30fps.mp4',
  'https://videos.pexels.com/video-files/7239170/7239170-hd_1920_1080_25fps.mp4',
]

export const copy = {
  en: {
    nav: ['About', 'Services', 'Insights', 'Partners', 'Launches', 'Listings', 'Reviews', 'Contact'],
    kicker: 'Licensed Real Estate Broker · Egypt',
    headline: 'Ask Ayman',
    subhead: '30 years guiding smarter investments.',
    lead: 'MBA. Licensed real-estate brokerage under Egyptian law. Three decades of multinational sales and customer care. Your trusted guide for residential, chalets, primary, and resale — across Egypt, the UAE, and Greece.',
    ctaAsk: 'Ask Ayman on WhatsApp',
    ctaCall: 'Call now',
    destinationsLabel: 'Markets',
    licenseBadge: 'Licensed in Egypt',
    licenseBadgeSub: 'Brokerage law',
    nawyBadge: 'Nawy verified',
    nawyBadgeSub: 'Agent',
    destinationsTitle: 'Where Ayman works',
    destinationsLead: 'Three markets of trust — with Egypt’s key destinations highlighted.',
    nawyPartnerTitle: 'Partnered with Nawy',
    nawyPartnerText:
      'Ayman is a Nawy verified agent. Explore listings and mortgages on Nawy.',
    nawyPartnerCta: 'Verified agent · Mortgages on Nawy',
    stats: [
      { value: '30+', label: 'Years of experience' },
      { value: '3', label: 'Countries of trust' },
      { value: 'MBA', label: 'Business leadership' },
      { value: '1:1', label: 'Personal guidance' },
    ],
    aboutTitle: 'Honesty in every transaction.',
    aboutBody:
      'Ayman Milad is a Heliopolis-based licensed real-estate broker under Egyptian brokerage law, with more than 30 years in multinational sales and customer service. He does not sell hype. He tells you the truth before you buy — because not every expensive property is a successful investment.',
    aboutTimingTitle: 'Updates, so you move at the right moment.',
    aboutTimingBody:
      'Ayman stays with the unit after the first conversation. He shares what changed on your shortlist — availability, payment plans, and price moves — so you can buy or sell when the timing is actually in your favor.',
    aboutTimingSteps: [
      { label: 'Your units', text: 'Status on the homes and resales you are watching.' },
      { label: 'Price changes', text: 'When a number moves up, down, or a plan gets better.' },
      { label: 'The call', text: 'A clear yes, wait, or sell — before the window closes.' },
    ],
    aboutPoints: [
      'Licensed real-estate brokerage in Egypt',
      'Nawy verified agent',
      'Unit and price updates for buy and sell timing',
      'Trusted across Egypt, UAE & Greece',
    ],
    servicesTitle: 'Where Ayman guides you',
    servicesLead: 'Residential. Chalets. Primary. Resale. One advisor who stays with the deal.',
    services: [
      {
        title: 'Residential',
        text: 'Homes in Cairo and beyond — chosen for lifestyle, location, and long-term value.',
      },
      {
        title: 'Chalets',
        text: 'Coastal and leisure properties with a clear view of seasonality, yield, and exit.',
      },
      {
        title: 'Primary market',
        text: 'New developments, payment plans, and developer selection without the noise.',
      },
      {
        title: 'Resale',
        text: 'Negotiated resale with market honesty — price, papers, and timing that make sense.',
      },
    ],
    insightsTitle: 'Ask Ayman first',
    insightsLead: 'The same advice he shares with clients — straight from his studio.',
    insights: [
      {
        title: 'Your budget is your secret',
        text: 'How much is your investment budget? The first mistake is answering that to the wrong person.',
        image: 'images/reel-budget.jpg',
        href: 'https://www.instagram.com/aymanmilad_property_consultant/reel/DdbUunqnXdb/',
      },
      {
        title: 'If I started from zero',
        text: 'If I began a real-estate investment from scratch, I would only do three things.',
        image: 'images/insight-start.jpg',
        href: 'https://www.instagram.com/aymanmilad_property_consultant/p/DdWqkZzj3fb/',
      },
      {
        title: 'Price is not the strategy',
        text: 'Thirty years taught him this: not every expensive property equals a successful investment.',
        image: 'images/insight-price.jpg',
        href: 'https://www.instagram.com/aymanmilad_property_consultant/p/DdCLgEbDc2g/',
      },
    ],
    partnersTitle: 'Partner compounds',
    partnersLead:
      'SODIC and Taj City in Egypt, plus flagship names in Greece and the UAE — filter by budget, then fly the map.',
    partnersAll: 'All SODIC compounds',
    partnersHint: 'Pick a compound, or use the arrows to fly the map.',
    partnersPrev: 'Previous compound',
    partnersNext: 'Next compound',
    partnersExplore: 'On the map',
    partnersSold: 'Landmark community',
    partnersView: 'Map view',
    partnersView2d: '2D',
    partnersView3d: '3D',
    partnersGreenery: 'Greenery',
    partnersLife: 'Life',
    contactTitle: 'Let’s talk about the next property.',
    contactLead: 'Need help? Call Ayman, write on WhatsApp, or visit the Heliopolis office.',
    formName: 'Your name',
    formPhone: 'Phone',
    formIntent: 'I want to',
    intents: ['Invest', 'Buy a home', 'Find a chalet', 'Sell / resale'],
    formMessage: 'Tell Ayman what you are looking for',
    formSubmit: 'Send on WhatsApp',
    visit: 'Visit',
    follow: 'Follow the conversation',
    footer: 'Ask Ayman · Licensed Real Estate Broker · Egypt · Nawy verified agent.',
    launchesTitle: 'New launches',
    launchesLead:
      'Fresh compounds from Nawy’s new launches, refreshed once a day. Ayman checks the plan, the developer, and whether the timing fits you.',
    launchesFrom: 'From',
    launchesAsk: 'Ask Ayman',
    launchesOnNawy: 'On Nawy',
    launchesUpdated: 'Updated',
    launchesEmpty: 'Launches will show here after the next daily refresh.',
    listingsTitle: 'Listings',
    listingsLead:
      'Indicative starting prices from partner compounds. Ayman confirms the live number, the unit, and whether now is the moment to buy or sell.',
    listingsFrom: 'From',
    listingsAsk: 'Ask about this',
    listingsNote: 'Published ranges, not a live quote. Updated with Ayman before you decide.',
    listingsCards: 'Cards',
    listingsMap: 'Map',
    listingsPrev: 'Previous',
    listingsNext: 'Next',
    listingsPage: 'Page',
    listingsAreaNote: 'Areas only — the pin is offset on purpose, not the compound gate.',
    reviewsTitle: 'Happy customers',
    reviewsLead: 'What clients say after Ayman stayed with the unit — and the price — until the timing was right.',
    reviews: [
      {
        name: 'Mariam',
        place: 'New Cairo',
        text: 'He kept sending the real price moves, not a brochure. We bought when the plan actually improved, not when the sales office was loudest.',
      },
      {
        name: 'Karim',
        place: 'Heliopolis',
        text: 'I was ready to overpay on a resale. Ayman showed me the last two closes and told me to wait a week. That week saved the deal.',
      },
      {
        name: 'Nour',
        place: 'North Coast',
        text: 'I wanted a chalet for the family and a number that still made sense in winter. He tracked availability until the right unit opened.',
      },
      {
        name: 'Hany',
        place: 'Sheikh Zayed',
        text: 'Selling was the hard part. He told us when demand picked up and we listed then — not six months earlier at a weaker price.',
      },
    ],
  },
  ar: {
    nav: ['عن أيمن', 'الخدمات', 'نصائح', 'الشركاء', 'إطلاقات', 'العروض', 'آراء العملاء', 'تواصل'],
    kicker: 'وسيط عقاري مرخص · مصر',
    headline: 'اسأل أيمن',
    subhead: '٣٠ سنة… بنوجّه استثمارك بذكاء.',
    lead: 'ماجستير إدارة أعمال، ووسيط عقاري مرخص بموجب قانون الوساطة العقارية في مصر، وخبرة أكتر من ٣٠ سنة في المبيعات وخدمة العملاء. دليلك الموثوق في السكن، الشاليهات، السوق الأساسي وإعادة البيع — في مصر، الإمارات، واليونان.',
    ctaAsk: 'اسأل أيمن على واتساب',
    ctaCall: 'اتصل دلوقتي',
    destinationsLabel: 'الأسواق',
    licenseBadge: 'مرخص في مصر',
    licenseBadgeSub: 'قانون الوساطة',
    nawyBadge: 'وكيل نوي المعتمد',
    nawyBadgeSub: 'شريك',
    destinationsTitle: 'فين أيمن بيشتغل',
    destinationsLead: 'ثلاث أسواق ثقة — مع إبراز وجهات مصر الأساسية.',
    nawyPartnerTitle: 'شراكة مع نوي',
    nawyPartnerText: 'أيمن وكيل نوي معتمد. اكتشف العقارات والتمويل العقاري على نوي.',
    nawyPartnerCta: 'وكيل معتمد · التمويل العقاري على نوي',
    stats: [
      { value: '٣٠+', label: 'سنة خبرة' },
      { value: '٣', label: 'دول بتثق فيه' },
      { value: 'MBA', label: 'قيادة أعمال' },
      { value: '١:١', label: 'استشارة شخصية' },
    ],
    aboutTitle: 'أمانة وخبرة في كل صفقة.',
    aboutBody:
      'أيمن ميلاد وسيط عقاري مرخص بموجب قانون الوساطة العقارية في مصر، من مصر الجديدة، بخبرة أكتر من ٣٠ سنة في المبيعات وخدمة العملاء على مستوى شركات عالمية. مش بيبيع ضجيج. بيقولك الحقيقة قبل ما تشتري — لأن مش كل عقار غالي يبقى استثمار ناجح.',
    aboutTimingTitle: 'تحديثات عشان تتحرك في الوقت الصح.',
    aboutTimingBody:
      'أيمن بيفضل مع الوحدة بعد أول مكالمة. بيشاركك اللي اتغير على قائمتك — التوافر، أنظمة السداد، وتحركات السعر — عشان تشتري أو تبيع لما التوقيت فعلاً يكون في صالحك.',
    aboutTimingSteps: [
      { label: 'وحداتكم', text: 'حالة البيوت والريسيل اللي بتتابعوها.' },
      { label: 'تغير الأسعار', text: 'لما الرقم يزيد أو ينزل، أو الخطة تتحسن.' },
      { label: 'القرار', text: 'اشتري، استنى، أو بيع — قبل ما الفرصة تقفل.' },
    ],
    aboutPoints: [
      'وسيط عقاري مرخص في مصر',
      'وكيل نوي المعتمد',
      'تحديثات الوحدات والأسعار لتوقيت الشراء والبيع',
      'ثقة في مصر والإمارات واليونان',
    ],
    servicesTitle: 'فين أيمن يقدر يساعدك',
    servicesLead: 'سكني. شاليهات. سوق أساسي. إعادة بيع. مستشار واحد ماشي مع الصفقة لحد الآخر.',
    services: [
      {
        title: 'سكني',
        text: 'بيت في القاهرة أو خارجها — نختاره على المعيشة، الموقع، والقيمة على المدى الطويل.',
      },
      {
        title: 'شاليهات',
        text: 'عقارات ساحلية وترفيهية بنظرة واضحة على الموسم، العائد، وفرصة الخروج.',
      },
      {
        title: 'السوق الأساسي',
        text: 'مشاريع جديدة، أنظمة سداد، واختيار مطور من غير شوشرة السوق.',
      },
      {
        title: 'إعادة البيع',
        text: 'ريسيل بتفاوض أمين — السعر، الأوراق، والتوقيت اللي فعلاً ينفعك.',
      },
    ],
    insightsTitle: 'اسأل أيمن الأول',
    insightsLead: 'نفس النصيحة اللي بيقولها لعملائه — من الاستوديو بتاعه.',
    insights: [
      {
        title: 'الميزانية في سرك',
        text: 'ميزانيتك كام للاستثمار؟ وأول غلطة إنك تقول الرقم للشخص الغلط.',
        image: 'images/reel-budget.jpg',
        href: 'https://www.instagram.com/aymanmilad_property_consultant/reel/DdbUunqnXdb/',
      },
      {
        title: 'لو هبدأ من الصفر',
        text: 'لو هبدأ استثمار عقاري من الصفر، هعمل ٣ حاجات بس.',
        image: 'images/insight-start.jpg',
        href: 'https://www.instagram.com/aymanmilad_property_consultant/p/DdWqkZzj3fb/',
      },
      {
        title: 'السعر مش الاستراتيجية',
        text: '٣٠ سنة في العقارات علّمته حاجة مهمة: مش كل عقار غالي = استثمار ناجح.',
        image: 'images/insight-price.jpg',
        href: 'https://www.instagram.com/aymanmilad_property_consultant/p/DdCLgEbDc2g/',
      },
    ],
    partnersTitle: 'كمباوندات الشركاء',
    partnersLead:
      'سوديك وتاج سيتي في مصر، وأسماء كبيرة في اليونان والإمارات — فلتر بالميزانية وبعدين طير على الخريطة.',
    partnersAll: 'كل كمباوندات سوديك',
    partnersHint: 'اختار كمباوند، أو استخدم الأسهم عشان تطير على الخريطة.',
    partnersPrev: 'الكمباوند السابق',
    partnersNext: 'الكمباوند التالي',
    partnersExplore: 'ظاهر على الخريطة',
    partnersSold: 'كمباوند معلم',
    partnersView: 'عرض الخريطة',
    partnersView2d: '2D',
    partnersView3d: '3D',
    partnersGreenery: 'خضرة',
    partnersLife: 'حياة',
    contactTitle: 'خلينا نتكلم عن العقار الجاي.',
    contactLead: 'محتاج مساعدة؟ اتصل بأيمن، ابعت واتساب، أو زور مكتب مصر الجديدة.',
    formName: 'اسمك',
    formPhone: 'الموبايل',
    formIntent: 'عايز',
    intents: ['أستثمر', 'أشتري بيت', 'أدور على شاليه', 'أبيـع / ريسيل'],
    formMessage: 'قول لأيمن بتدور على إيه',
    formSubmit: 'ابعت على واتساب',
    visit: 'المكتب',
    follow: 'تابع الحوار',
    footer: 'اسأل أيمن · وسيط عقاري مرخص · مصر · وكيل نوي المعتمد.',
    launchesTitle: 'إطلاقات جديدة',
    launchesLead:
      'كمباوندات جديدة من قسم الإطلاقات على نوي، بتتحدث مرة كل يوم. أيمن بيراجع الخطة والمطور وهل التوقيت مناسب ليك.',
    launchesFrom: 'يبدأ من',
    launchesAsk: 'اسأل أيمن',
    launchesOnNawy: 'على نوي',
    launchesUpdated: 'آخر تحديث',
    launchesEmpty: 'الإطلاقات هتظهر هنا بعد التحديث اليومي الجاي.',
    listingsTitle: 'العروض',
    listingsLead:
      'أسعار استرشادية تبدأ من كمباوندات الشركاء. أيمن بيأكد الرقم الحالي والوحدة، وهل الوقت مناسب للشراء أو البيع.',
    listingsFrom: 'يبدأ من',
    listingsAsk: 'اسأل عن العرض',
    listingsNote: 'نطاقات منشورة، مش تسعير لحظي. اتأكد مع أيمن قبل القرار.',
    listingsCards: 'بطاقات',
    listingsMap: 'خريطة',
    listingsPrev: 'السابق',
    listingsNext: 'التالي',
    listingsPage: 'صفحة',
    listingsAreaNote: 'مناطق تقريبية — الدبوس متعمد إنه مش على بوابة الكمباوند.',
    reviewsTitle: 'آراء العملاء',
    reviewsLead: 'كلام العملاء بعد ما أيمن فضل متابع الوحدة والسعر لحد ما التوقيت يبقى مناسب.',
    reviews: [
      {
        name: 'مريم',
        place: 'القاهرة الجديدة',
        text: 'كان بيبعت تحركات السعر الحقيقية، مش بروشور. اشترينا لما الخطة فعلاً اتحسنت، مش لما مكتب المبيعات كان أعلى صوت.',
      },
      {
        name: 'كريم',
        place: 'مصر الجديدة',
        text: 'كنت هدفع زيادة في ريسيل. أيمن ورّاني آخر صفقتين وقال استنى أسبوع. الأسبوع ده وفّر الصفقة.',
      },
      {
        name: 'نور',
        place: 'الساحل الشمالي',
        text: 'عايزة شاليه للعائلة برقم لسه منطقي في الشتا. فضل متابع التوافر لحد ما الوحدة المناسبة اتفتحت.',
      },
      {
        name: 'هاني',
        place: 'الشيخ زايد',
        text: 'البيع كان الأصعب. قالنا امتى الطلب زاد ونزلنا الإعلان ساعتها — مش قبلها بستة شهور بسعر أضعف.',
      },
    ],
  },
}
